catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (CategoryDetailView, CategoryListView, ContactsView,
                           ProductDetailView, ProductListView,
                           SearchView, CompanyListView, AccountListView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/product/', ProductListView.as_view(), name='product_list'),
    path(
        'category/product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'
    ),
    # path('', HomeListView.as_view(), name='home_list'),
    path('search/', SearchView.as_view(), name='search'),
    path('company/', CompanyListView.as_view(), name='company_list'),
    path('account/', AccountListView.as_view(), name='account_list'),
    # path('create_appointment/', create_appointment, name='create_appointment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from catalog.views import ContactsView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>", email_verification, name="email-confirm"),
]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="product/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите фото категории",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование продукта",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    price = models.IntegerField(
        blank=True, null=True, verbose_name="Цена", help_text="Укажите цену за покупку"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию",
        null=True,
        blank=True,
        related_name="categories",
    )
    restrictions = models.TextField(
        verbose_name="Ограничения",
        help_text="Укажите любые ограничения на продукт",
        blank=True,
        null=True,
    )
    medical_indications = models.TextField(
        verbose_name="Медицинские показания",
        help_text="Укажите медицинские показания",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Название компании",
        help_text="Введите название компании",
    )
    description = models.TextField(
        verbose_name="Описание компании",
        help_text="Введите описание компании",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="product/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите фото компании",
    )

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Имя",
        help_text="Введите ваше имя",
    )
    surname = models.CharField(
        max_length=150,
        verbose_name="Фамилия",
        help_text="Введите вашу фамилию",
    )
    patronymic = models.CharField(
        max_length=150,
        verbose_name="Отчество",
        help_text="Введите ваше отчество",
        blank=True,
        null=True,
    )
    email = models.EmailField(
        verbose_name="Email",
        help_text="Введите ваш email",
    )
    phone = models.CharField(
        max_length=35,
        verbose_name="Телефон",
        help_text="Введите ваш номер телефона",
    )
    appointment = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        verbose_name="Запись на прием",
        help_text="Введите, куда вы хотите записаться",
        null=True,
        blank=True,
    )
    token = models.CharField(
        max_length=100, verbose_name="token", blank=True, null=True
    )

    class Meta:
        verbose_name = "Аккаунт"
        verbose_name_plural = "Аккаунты"

    def __str__(self):
        return self.name


# class Appointment(models.Model):
#     name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
#     appointment_date = models.DateField()
#     appointment_time = models.TimeField()
#     service_type = models.CharField(max_length=255)
#     phone = models.CharField(max_length=35)
#     email = models.EmailField()
#
#
# class DiagnosticResult(models.Model):
#     appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
#     test_name = models.CharField(max_length=255)
#     result = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

catalog/forms.py
from django.forms import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"

catalog/views.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView

from catalog.models import Category, Product, Company, Account


# class HomeListView(ListView):
#     model = Home


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contacts"] = Product.objects.all()[:5]
        return context


class CategoryListView(ListView):
    model = Category


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = Product.objects.filter(category=self.object)
        return context


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")


class SearchView(TemplateView):
    model = Product
    template_name = "catalog/search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        print(query)
        return Product.objects.filter(name__icontains=query)


class CompanyListView(ListView):
    model = Company


class AccountListView(ListView):
    model = Account


# def create_appointment(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         surname = request.POST.get('surname')
#         phone = request.POST.get('phone')
#         email = request.POST.get('email')
#         appointment_date = request.POST.get('appointment_date')
#         appointment_time = request.POST.get('appointment_time')
#
#         appointment = Appointment(name=name, phone=phone, surname=surname, email=email,
#                                   appointment_date=appointment_date,
#                                   appointment_time=appointment_time)
#         appointment.save()
#
#         return redirect('catalog:account_list')
#
#     return render(request, 'catalog/account_list.html', {'create_appointment': create_appointment})


# def diagnostic_results(request, appointment_id):
#     diagnostic_results = DiagnosticResult.objects.filter(appointment_id=appointment_id)
#     return render(request, 'catalog/account_list.html', {'diagnostic_results': diagnostic_results})

catalog/templates/catalog/includes/inc_menu.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'catalog:category_list' %}">ЗДОРОВЬЕ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'catalog:category_list' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'catalog:contacts' %}">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-disabled="true" href="{% url 'catalog:company_list' %}">О компании</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link active" type="submit">Выход</button>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-disabled="true" href="{% url 'catalog:account_list' %}">Личный кабинет</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-disabled="true" href="{% url 'users:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-disabled="true" href="{% url 'users:register' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
<!--            <form class="d-flex" role="search" method="get" action="{% url 'catalog:search' %}">-->
<!--                 {% csrf_token %}-->
<!--                <input class="btn btn-light me-2" type="search" placeholder="Поиск на сайте" aria-label="Search" name="q">-->
<!--                <button class="btn btn-outline-light" type="submit">Поиск</button>-->
<!--            </form>-->
        </div>
    </div>
</nav>