catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (CategoryDetailView, CategoryListView, ContactsView,
                           ProductDetailView, ProductListView,
                           SearchView, CompanyListView, AccountListView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('category/product/', ProductListView.as_view(), name='product_list'),
    path(
        'category/product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'
    ),
    # path('', HomeListView.as_view(), name='home_list'),
    path('search/', SearchView.as_view(), name='search'),
    path('company/', CompanyListView.as_view(), name='company_list'),
    path('account/', AccountListView.as_view(), name='account_list'),
    # path('create_appointment/', create_appointment, name='create_appointment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from catalog.views import ContactsView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("", include("catalog.urls", namespace="catalog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>", email_verification, name="email-confirm"),
]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    description = models.TextField(
        verbose_name="Описание категории",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="product/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите фото категории",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Наименование продукта",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
        blank=True,
        null=True,
    )
    price = models.IntegerField(
        blank=True, null=True, verbose_name="Цена", help_text="Укажите цену за покупку"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию",
        null=True,
        blank=True,
        related_name="categories",
    )
    restrictions = models.TextField(
        verbose_name="Ограничения",
        help_text="Укажите любые ограничения на продукт",
        blank=True,
        null=True,
    )
    medical_indications = models.TextField(
        verbose_name="Медицинские показания",
        help_text="Укажите медицинские показания",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Название компании",
        help_text="Введите название компании",
    )
    description = models.TextField(
        verbose_name="Описание компании",
        help_text="Введите описание компании",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        upload_to="product/photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите фото компании",
    )

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Имя",
        help_text="Введите ваше имя",
    )
    surname = models.CharField(
        max_length=150,
        verbose_name="Фамилия",
        help_text="Введите вашу фамилию",
    )
    patronymic = models.CharField(
        max_length=150,
        verbose_name="Отчество",
        help_text="Введите ваше отчество",
        blank=True,
        null=True,
    )
    email = models.EmailField(
        verbose_name="Email",
        help_text="Введите ваш email",
    )
    phone = models.CharField(
        max_length=35,
        verbose_name="Телефон",
        help_text="Введите ваш номер телефона",
    )
    appointment = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        verbose_name="Запись на прием",
        help_text="Введите, куда вы хотите записаться",
        null=True,
        blank=True,
    )
    token = models.CharField(
        max_length=100, verbose_name="token", blank=True, null=True
    )

    class Meta:
        verbose_name = "Аккаунт"
        verbose_name_plural = "Аккаунты"

    def __str__(self):
        return self.name


# class Appointment(models.Model):
#     name = models.ForeignKey('auth.User', on_delete=models.CASCADE)
#     appointment_date = models.DateField()
#     appointment_time = models.TimeField()
#     service_type = models.CharField(max_length=255)
#     phone = models.CharField(max_length=35)
#     email = models.EmailField()
#
#
# class DiagnosticResult(models.Model):
#     appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
#     test_name = models.CharField(max_length=255)
#     result = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

catalog/forms.py
from django.forms import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"

catalog/views.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView

from catalog.models import Category, Product, Company, Account


# class HomeListView(ListView):
#     model = Home


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contacts"] = Product.objects.all()[:5]
        return context


class CategoryListView(ListView):
    model = Category


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = Product.objects.filter(category=self.object)
        return context


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")


class SearchView(TemplateView):
    model = Product
    template_name = "catalog/search.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        print(query)
        return Product.objects.filter(name__icontains=query)


class CompanyListView(ListView):
    model = Company


class AccountListView(ListView):
    model = Account


# def create_appointment(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         surname = request.POST.get('surname')
#         phone = request.POST.get('phone')
#         email = request.POST.get('email')
#         appointment_date = request.POST.get('appointment_date')
#         appointment_time = request.POST.get('appointment_time')
#
#         appointment = Appointment(name=name, phone=phone, surname=surname, email=email,
#                                   appointment_date=appointment_date,
#                                   appointment_time=appointment_time)
#         appointment.save()
#
#         return redirect('catalog:account_list')
#
#     return render(request, 'catalog/account_list.html', {'create_appointment': create_appointment})


# def diagnostic_results(request, appointment_id):
#     diagnostic_results = DiagnosticResult.objects.filter(appointment_id=appointment_id)
#     return render(request, 'catalog/account_list.html', {'diagnostic_results': diagnostic_results})

catalog/templates/catalog/account_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}

<div class="row">
    <div class="col-lg-4 my-3 position-relative">
        <nav id="navbar-example3" class="h-100 flex-column align-items-stretch pe-4 border-end">
            <nav class="nav nav-pills flex-column">
                <a class="nav-link" href="#Запись на прием">Запись на прием</a>
                <a class="nav-link" href="#История записей">История записей и результаты диагностик</a>
            </nav>
        </nav>
    </div>

    <div class="col-8 my-3 position-relative">
        <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true"
             class="scrollspy-example-2" tabindex="0">

            <span class="placeholder col-12 bg-primary"></span>

            <div id="Запись на прием">
                <h4>Запись на прием</h4>
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <form method="post" action="/create_appointment">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <label for="name" class="form-label">Имя</label>
                                    <input type="text" class="form-control" id="name"
                                           placeholder="Введите ваше имя" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="surname" class="form-label">Фамилия</label>
                                    <input type="text" class="form-control" id="surname"
                                           placeholder="Введите вашу фамилию" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="phone" class="form-label">Телефон</label>
                                    <input type="text" class="form-control" id="phone"
                                           placeholder="Введите ваш номер телефона" value="" required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="email" class="form-control" id="email"
                                           placeholder="Введите ваш email" value=""
                                           required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="appointment" class="form-label">Услуга</label>
                                    <input type="text" class="form-control" id="appointment"
                                           placeholder="Введите услугу, куда вы хотите записаться" value=""
                                           required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="appointment_date" class="form-label">Дата</label>
                                    <input type="date" class="form-control" id="appointment_date"
                                           placeholder="Введите услугу, куда вы хотите записаться" value=""
                                           required>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="appointment_time" class="form-label">Время</label>
                                    <input type="time" class="form-control" id="appointment_time"
                                           placeholder="Введите услугу, куда вы хотите записаться" value=""
                                           required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Записаться</button>
                        </form>
                    </div>
                </div>

                <span class="placeholder col-12 bg-primary"></span>

                <div id="История записей">
                    <h4>История записей и результаты диагностик</h4>
                    <p>
                    <div class="col-md-12">
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                            <div class="container">
                                <div class="accordion" id="accordionExample">
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="heading1">
                                            <button class="accordion-button" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#collapse1"
                                                    aria-expanded="false" aria-controls="collapse1">
                                                Запись № 1
                                            </button>
                                        </h2>
                                        <div id="collapse1" class="accordion-collapse collapse show"
                                             aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                            <div class="accordion-body">
                                                <table class="table table-white table-hover">
                                                    <thead>
                                                    <tr>
                                                        <th>Услуга</th>
                                                        <th>Цена</th>
                                                        <th>Дата</th>
                                                        <th>Время</th>
                                                        <th>Результат</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody class="table table-primary table-hover">
                                                    <tr>
                                                        <td><a class="text-dark">Группа крови</a></td>
                                                        <td>740 рублей</td>
                                                        <td>13.08.2024</td>
                                                        <td>13:00</td>
                                                        <td>Первая группа крови</td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                                <div class="d-flex justify-content-between">
                                                    <p><strong>Итого:</strong></p>
                                                    <p><strong>740 рублей</strong></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="heading2">
                                            <button class="accordion-button collapsed" type="button"
                                                    data-bs-toggle="collapse" data-bs-target="#collapse2"
                                                    aria-expanded="false" aria-controls="collapse2">
                                                Запись № 2
                                            </button>
                                        </h2>
                                        <div id="collapse2" class="accordion-collapse collapse"
                                             aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                            <div class="accordion-body">
                                                <table class="table table-white table-hover">
                                                    <thead>
                                                    <tr>
                                                        <th>Услуга</th>
                                                        <th>Цена</th>
                                                        <th>Дата</th>
                                                        <th>Время</th>
                                                        <th>Результат</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody class="table table-primary table-hover">
                                                    <tr>
                                                        <td><a class="text-dark">МРТ головы</a></td>
                                                        <td>5790 рублей</td>
                                                        <td>13.08.2024</td>
                                                        <td>15:30</td>
                                                        <td>За результатом рекомендуется обратиться к своему лечащему врачу.</td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                                 <div class="d-flex justify-content-between">
                                                    <p><strong>Итого:</strong></p>
                                                    <p><strong>5790 рублей</strong></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row">
    <div class="col my-3">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140"
             src="{{ category.photo | media_filter }}">
        <h2 class="fw-normal">{{ category.name }}</h2>
        <h2 class="lead">{{ category.description }}</h2>
        <p><a class="btn btn-secondary" href="{% url 'catalog:category_list' %}">Назад</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->
<div class="row">
    {% for product in products %}
    <div class="col-12 my-3 bg-primary-subtle p-3">
        <div> №{{ product.pk }}</div>
    <a href="{% url 'catalog:product_detail' product.id %}" class="link-underline link-underline-opacity-0 h4 d-block">{{ product.name|linebreaksbr }}</a>
    <p>{{ product.description|linebreaksbr }}</p>
        <hr>
    <p><b>Ограничения:</b> {{ product.restrictions|linebreaksbr }}</p>
    <p><b>Медицинские показания:</b> {{ product.medical_indications|linebreaksbr }}</p>
    <div><span class="badge rounded-pill text-bg-light">Цена: {{ product.price }} рублей</span></div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row">
    {% for category in object_list %}
    <div class="col-lg-4 my-3 position-relative">
                <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{{ category.photo | media_filter }}">
        <h2 class="fw-normal">{{ category.name }}</h2>
        <p class="lead">{{ category.description }}</p>
        <p><a class="btn btn-info" href="{% url 'catalog:category_detail' category.pk %}">Узнать больше</a></p>
    </div><!-- /.col-lg-4 -->
    {% endfor %}
</div><!-- /.row -->
{% endblock %}

catalog/templates/catalog/company_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load static %}
{% load my_tags %}
<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Здоровье</h2>
        <p class="lead"><b>Здоровье –</b> это онлайн-платформа, которая помогает вам взять под контроль свое здоровье,
            предоставляя удобный и доступный доступ к современным медицинским диагностическим инструментам. </p>
        <p class="lead"><b>Здоровье -</b> это не просто сайт, это ваш надежный партнер в заботе о своем здоровье. Мы
            предоставляем вам инструменты, знания и поддержку, чтобы вы могли принимать осознанные решения о своем
            благополучии.</p>
        <p class="lead"><b>Мы верим, что каждый человек заслуживает быть здоровым!</b></p>

    </div>
    <div class="col-md-5">
        <img src="{% static 'img/999.jpg' %}" class="bd-placeholder-img featurette-img"/>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">Почему Здоровье?</h2>
        <p class="lead"><b>Доступность:</b> Мы стремимся сделать медицинские услуги доступными для всех, независимо от
            местоположения и финансовых возможностей.</p>
        <p class="lead"><b>Простота:</b> Наша платформа разработана с учетом удобства использования, чтобы сделать
            процесс диагностики и
            получения медицинской информации максимально простым.</p>
        <p class="lead"><b>Точность:</b> Мы используем только проверенные медицинские инструменты и технологии, чтобы
            обеспечить точность
            результатов и рекомендаций.</p>
        <p class="lead"><b>Конфиденциальность:</b> Мы гарантируем конфиденциальность вашей медицинской информации и
            соблюдаем все
            необходимые стандарты безопасности.</p></p>
    </div>
    <div class="col-md-5 order-md-1">
        <img src="{% static 'img/888.jpg' %}" class="bd-placeholder-img featurette-img"/>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">История "Здоровье": Путь от мечты до реальности</h2>
        <p class="lead">"Здоровье" родилось из личной истории, истории одного человека, который столкнулся с серьезными
            проблемами со здоровьем. Оказавшись перед лицом сложной диагностики и множеством вопросов, он понял,
            насколько сложным и запутанным может быть мир медицины.</p>
        <p class="lead">Эта история стала отправной точкой для создания "Здоровье" – онлайн-платформы, которая должна
            была сделать медицинские знания и инструменты доступными для всех. Мы верили, что каждый человек должен
            иметь возможность самостоятельно следить за своим здоровьем, принимать информированные решения и получать
            качественную медицинскую помощь.</p>

    </div>
    <div class="col-md-5">
        <img src="{% static 'img/321.jpg' %}" class="bd-placeholder-img featurette-img"/>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">С самого начала мы поставили перед собой амбициозные цели:</h2>
        <p class="lead"><b>Сделать диагностику доступной:</b> Мы хотели, чтобы каждый мог получить доступ к современным
            диагностическим тестам, не выходя из дома.</p>
        <p class="lead"><b>Предоставить надежные знания:</b> Мы стремились собрать и систематизировать достоверную
            информацию о здоровье,
            заболеваниях и методах лечения, чтобы сделать ее доступной для широкой аудитории.</p>
        <p class="lead"><b>Создать сообщество заботы:</b> Мы хотели создать онлайн-пространство, где люди могли бы
            делиться опытом, получать
            поддержку и задавать вопросы о своем здоровье.</p>
    </div>
    <div class="col-md-5 order-md-1">
        <img src="{% static 'img/987.jpg' %}" class="bd-placeholder-img featurette-img"/>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Мы начали с небольшого коллектива энтузиастов, объединенных
            желанием сделать мир здоровее. </h2>
        <p class="lead">С помощью талантливых разработчиков, врачей и специалистов мы разработали удобную платформу,
            наполненную полезной информацией и практичными инструментами.</p>
        <p class="lead">Сегодня "Здоровье" – это динамично развивающийся проект, который помогает тысячам людей по всей
            стране заботиться о своем здоровье. Мы продолжаем совершенствовать платформу, добавляя новые функции,
            расширяя базу знаний и привлекая к сотрудничеству лучших специалистов в области медицины. </p>
        <p class="lead"><b>Наша миссия остается неизменной:</b> сделать здоровье доступным и понятным для всех!</p>

    </div>
    <div class="col-md-5">
        <img src="{% static 'img/111.jpg' %}" class="bd-placeholder-img featurette-img"/>
    </div>
</div>

<hr class="featurette-divider">

<div class="pricing-header px-3 py-3 pt-md-2 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Наша команда врачей</h1>
</div>

<div class="row">
    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/vrachiha.jpg' %}">
        <h2 class="fw-normal">Аверченко Мария Серафимовна</h2>
        <p class="lead">Врач-терапевт</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/333.jpg' %}">
        <h2 class="fw-normal">Авдеева Елена Александровна</h2>
        <p class="lead">Врач функциональной диагностики</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/vrach.jpg' %}">
        <h2 class="fw-normal">Аверков Антон Алексеевич</h2>
        <p class="lead">Врач ультразвуковой диагностики</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/435.png' %}">
        <h2 class="fw-normal">Белова Ольга Дмитриевна</h2>
        <p class="lead">Врач-эндокринолог</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/856.png' %}">
        <h2 class="fw-normal">Ахмедов Малик Мухтарович</h2>
        <p class="lead">Врач-эндоскопист</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="bd-placeholder-img rounded-circle" width="140" height="140" src="{% static 'img/965.jpg' %}">
        <h2 class="fw-normal">Беляева Людмила Александровна</h2>
        <p class="lead">Врач-невролог</p>
        <p><a class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 md-5">
        </div>
        <div class="row">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text"><b>{{ product.name|linebreaksbr }}</b></p>
                        <p class="card-text">{{ product.description|linebreaksbr }}</p>
                        <p class="card-text"><b>Ограничения:</b> {{ product.restrictions|linebreaksbr }}</p>
                        <p class="card-text"><b>Медицинские показания:</b> {{ product.medical_indications|linebreaksbr }}</p>
                        <p class="card-text"><b>Цена:</b> {{ product.price }} рублей</p>
                        <a type="button" class="btn btn-info" href="{% url 'catalog:account_list' %}">Записаться</a>
                        <a type="button" class="btn bg-info-subtle" href="{% url 'catalog:category_list' %}">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/search.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row mt-5">
    <div class="col-12">
        <form class="form-horizontal" method="get" action="{% url 'catalog:search' %}">
            {% csrf_token %}
            <input class="form-control" value="{{ request.GET.q }}" name="q">
        </form>
    </div>
    {% for product in object_list %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {{ product }}
            </div>
        </div>
    </div>
    {% endfor %}
</div><!-- /.row -->
{% endblock %}